IF EXISTS (SELECT * FROM SYS.DATABASES WHERE NAME = 'QALight')
BEGIN
    DECLARE @Msg VARCHAR(100)
    SET @Msg = 'DB QALight already exists!'
    PRINT @Msg
    RAISERROR(@Msg, 20, 1) WITH LOG
END
GO

CREATE DATABASE QALight COLLATE Ukrainian_CI_AS
GO

USE QALight
GO

CREATE TABLE SUBJECTS(
    ID int NOT NULL,
    NAME nvarchar(32) NOT NULL,
    HOURS int,
    SEMESTER smallint,
 CONSTRAINT PK_SUBJECTS PRIMARY KEY (ID)
)
GO 

CREATE TABLE UNIVERSITIES(
    ID int NOT NULL,
    NAME nvarchar(150) NOT NULL,
    RATING int,
    CITY nvarchar(32),
 CONSTRAINT PK_UNIVERSITIES PRIMARY KEY (ID)
)
GO

CREATE TABLE EXAM_MARKS(
    ID int IDENTITY(1,1) NOT NULL,
    STUDENT_ID int,
    SUBJ_ID int,
    MARK decimal(5,3),
    EXAM_DATE datetime,
 CONSTRAINT PK_EXAM_MARKS PRIMARY KEY (ID)
)
GO

CREATE TABLE SUBJ_LECT(
    LECTURER_ID int NOT NULL,
    SUBJ_ID int NOT NULL
 CONSTRAINT PK_SUBJ_LECT PRIMARY KEY (LECTURER_ID, SUBJ_ID)
)
GO

CREATE TABLE LECTURERS(
    ID int NOT NULL,
    SURNAME nvarchar(50) NOT NULL,
    NAME nvarchar(30),
    CITY nvarchar(50),
    UNIV_ID int,
 CONSTRAINT PK_LECTURERS PRIMARY KEY (ID)
)
GO

CREATE TABLE STUDENTS(
    ID int NOT NULL,
    SURNAME nvarchar(50) NOT NULL,
    NAME nvarchar(30),
    GENDER nchar(1),
    STIPEND decimal(18, 2),
    COURSE smallint DEFAULT(1),
    CITY nvarchar(50),
    BIRTHDAY datetime,
    UNIV_ID int,
 CONSTRAINT PK_STUDENTS PRIMARY KEY (ID)
)
GO

CREATE TABLE STUDENTS_ARCHIVE(
    ID int,
    SURNAME nvarchar(50),
    NAME nvarchar(30),
    GENDER nchar(1),
    STIPEND decimal(18, 2),
    COURSE smallint,
    CITY nvarchar(50),
    BIRTHDAY datetime,
    UNIV_ID int
)
GO

ALTER TABLE EXAM_MARKS ADD CONSTRAINT FK_EXAM_MARKS_STUDENT 
    FOREIGN KEY(STUDENT_ID)
        REFERENCES STUDENTS (ID)
GO

ALTER TABLE EXAM_MARKS ADD CONSTRAINT FK_EXAM_MARKS_SUBJECT 
    FOREIGN KEY(SUBJ_ID)
        REFERENCES SUBJECTS (ID)
GO

ALTER TABLE SUBJ_LECT ADD CONSTRAINT FK_SUBJ_LECT_LECTURER 
    FOREIGN KEY(LECTURER_ID)
        REFERENCES LECTURERS (ID)
GO

ALTER TABLE SUBJ_LECT ADD CONSTRAINT FK_SUBJ_LECT_SUBJECT 
    FOREIGN KEY(SUBJ_ID)
        REFERENCES SUBJECTS (ID)
GO

ALTER TABLE LECTURERS ADD CONSTRAINT FK_LECTURERS_UNIV 
    FOREIGN KEY(UNIV_ID)
        REFERENCES UNIVERSITIES (ID)
GO

ALTER TABLE STUDENTS ADD CONSTRAINT FK_STUDENTS_UNIV 
    FOREIGN KEY(UNIV_ID)
        REFERENCES UNIVERSITIES (ID)
GO
